cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns = [
    path('',CartView.as_view(),name="index"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('update/',UpdateCart.as_view(),name="update"),
    path('addCart/',AddCart.as_view(),name="addToCart"),
    path('delete/',deleteItem.as_view(),name="delete"),
]

product/urls.py
from django.urls import path
from .views import *
app_name='product'
urlpatterns = [
 
    path('',ProductView.as_view(),name="index"),
    path('category/<slug:slug>/',CategoryView.as_view(),name="category"),
    path('detail/<int:id>/',DetailView.as_view(),name="detail"),
    path('search/',SearchProduct.as_view(),name="search"),
    # path('create/',CreateProduct.as_view(),name="create"),
]

shopapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Account.urls')),
    path('',include('core.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('user/',include('user.urls')),
    path('order/',include('order.urls')),
    path('nhaphang/',include('nhaphang.urls')),
]

cart/models.py
from django.db import models
from product.models import Product
from user.models import CustomerUser
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    create_at =models.DateTimeField(auto_now_add=True)
    update_at =models.DateTimeField(auto_now=True)
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    item=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)

cart/views.py
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import CartItem,Cart
from user.models import *
from product.models import *
from order.models import *
from django.views import View
# Create your views here.
class CartView(View):
    def get(seft,request):
        context={}
        if request.user.is_authenticated:
            cart=Cart.objects.get(user=CustomerUser.objects.get(id=request.user.id))
            if(cart):
                cartItems= cart.cartitem_set.all()
                if cartItems.count() ==0:
                    return render(request,"cart/cartEmpty.html")
                else:
                    total=0
                    for cart in cartItems:
                        cart.total= int(cart.quantity)*int(cart.item.sale_price)
                        total = total+ int(cart.quantity)*int(cart.item.sale_price)
                    context['list'] =cartItems 
                    context['total']= total
                    # return HttpResponse(cartItems[0].total)
                    return render(request, "cart/cart.html",context)
        else:
            return redirect('account:login')
class deleteItem(View):
    def post(self,request):
        item =request.POST.get('cartItem')
        CartItem.objects.get(pk=item).delete()
        return HttpResponse(1)
class AddCart(View):
    def post(seft,request):
        if(request.is_ajax()):
            product_id = request.POST.get('product_id')
            product_number = request.POST.get('product_number')
            if(request.user.id is not None):
                cart=Cart.objects.get(user=CustomerUser.objects.get(id=request.user.id))
                if(not cart):
                    cart=Cart.objects.create(user=CustomerUser.objects.get(id=request.user.id))
                    return HttpResponse(cart)
                else:

                    pro=Product.objects.get(pk=product_id)
                    item= CartItem.objects.filter(item=pro,cart=cart)
                    if(not item):
                        CartItem.objects.create(cart= cart,item= pro,quantity= product_number)
                    else:
                       item.quantity =int(item.quantity) + int(product_number)
                       item.save()
                return HttpResponse(item)
                   
class CheckoutView(View):
    def get(seft,request):
        context={}
        if request.user.is_authenticated:
            cart=Cart.objects.get(user=CustomerUser.objects.get(id=request.user.id))
            user = CustomerUser.objects.get(id=request.user.id)
            add= Address.objects.filter(user = user,default = True)
            list_address = Address.objects.filter(user=user)
            
            if len(add)==0:
                temp = list_address[0]
                print(temp.default)
                temp.default = True
                temp.save()
                list_address = Address.objects.filter(user=user)
                add = Address.objects.filter(user = user,default = True)
            # print(add[0])
            # address= add.ToString()
               
            print(len(add))
            ship=Shipping.objects.all()
            context['ship']= ship
            payment = Payment.objects.all()
            context['payment']= payment
            if(cart):
                cartItems= cart.cartitem_set.all()
                total=0
                for cart in cartItems:
                    cart.total= int(cart.quantity)*int(cart.item.sale_price)
                    total = total+ int(cart.quantity)*int(cart.item.sale_price)
                context['list'] =cartItems 
                context['total']= total
                context['address']= add[0]
                context['list_add']= list_address
            return render(request,"cart/checkout.html",context)

class UpdateCart(View):
    def post(self, request):
        if request.user.is_authenticated:
          
            quantity = request.POST.get('quantity')
            cart_id = request.POST.get('cart_id')
            cartItem = CartItem.objects.get(pk=cart_id)
            cartItem.quantity = quantity
            cartItem.save()
        return HttpResponse(quantity)

templates/cart/cart.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load mathfilters %}

{% block contentblock %}
  <!--Main layout-->
  <main style="padding-top:100px;">
      <div class="cart container-fluid">
          <h2>Giỏ hàng</h2>
          <div class="row mt-5 pl-4">
              <div class="col-md-9 ">
                  <div class="content  border p-5">
                      {% for cartItem in list %}
                      <div class="row mb-5">
                          <div class="col-md-3">
                              <img src="{{cartItem.item.thumbnail}}" alt="">
                          </div>
                          <div class="col-md-5">
                              <h5>{{cartItem.item.title}}</h5>
                              <div class="m-4">
                                <button  name="delete_item" data-id="{{cartItem.id}}">Xóa khỏi giỏ hàng</button>
                                
                            </div>
                          </div>
                          <div class="col-md-4">
                            <span>Price:</span><strong class="price-product">{{cartItem.item.sale_price}}</strong>
                              <div class="my-3"><button data-id="{{cartItem.id}}" class="increase" type="button">+</button><input  class="text-center" type="text" name="quantity" id="{{cartItem.id}}" maxlength="2" size="1" value="{{cartItem.quantity}}" min=1 max=100><button data-id="{{cartItem.id}}" class="decrease">-</button>
                              </div>
                              <span>Total:</span><strong class="price-product">{{cartItem.item.sale_price|mul:cartItem.quantity}}</strong>
                            </div>
                      </div>
                      {% endfor %}
                
                   
                  </div>
              </div>
              <div class="col-md-3 border">
                    <div class="total m-3">
                        <div class="row py-4 border">
                            <div class="col-md-12 d-flex justify-content-between">
                                <strong>Tổng tiền</strong>
                                <span class="price-product">{{total}}</span>
                            </div>
                        </div>
                        <div class="row py-4 ">
                            <div class="col-md-12 d-flex justify-content-between">
                              <a href="{% url 'cart:checkout'%}" type="submit" class="btn btn-success">Tiến hành mua hàng</a>
                            </div>
                        </div>
                    </div>
              </div>
            </div>

      </div>
      <!--Section: Products v.3-->
      <!--Pagination-->
      
  </main>
{%endblock%}

  

templates/cart/cartEmpty.html
{% extends 'homepage/base.html' %}
{% load static %}


{% block contentblock %}
  <!--Main layout-->
  <main style="padding-top:100px;">
      <div class="cart container-fluid">
          <h2>Giỏ hàng</h2>
            <div class="row d-flex align-items-center justify-content-center">
                <div class="col-md-6 p-5">
                    <img src="https://bizweb.dktcdn.net/100/411/922/themes/800986/assets/empty-cart.png?1607914671664" alt="">
                   
                </div>
                <div class="col-md-3"> <a href="{%url 'product:index'%}" class="btn btn-danger" style="width: 200px;display: inline-block;">Mua ngay</a></div>
            </div>

      </div>
      <!--Section: Products v.3-->
      <!--Pagination-->
      
  </main>
{%endblock%}

  

templates/cart/checkout.html
{% extends 'homepage/base.html' %}
{% load static %}


{% block contentblock %}
<!--Main layout-->
<main style="padding-top:100px;">
    <div class="cart container-fluid">
        <h2 class="ml-2">Thanh toán</h2>
      
        <div class="row m-3 border">
            <div class="col-12">
                <h5 class="text-danger">Địa chỉ nhận hàng</h5>
                <div class="address_user">
                    <div class="row mt-2">
                        <div class="col-md-3">
                            <h4>{{address.reciever}} </h4>
                            <strong>{{address.phone_reciever}}</strong>
                        </div>
                        <div class="col-md-7">
                            <p class="address" name="address">{{address.ToString}}</p>
                        </div>
                        <div class="col-md-2 text-center">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#change_address">Thay đổi</button>
                            <div class="modal fade" id="change_address" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLongTitle">Chọn địa chỉ</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                      <h4>Chọn địa chỉ.</h4>
                                      <form>
                                        {%for a in list_add%}
                                            <div class="radio">
                                                <label><input style="margin-right: 5px;align-self: left;" type="radio" value="{{a.id}}" name="option_address" checked>{{a.ToString}}</label>
                                            </div>
                                        {%endfor%}
                                        
                                    </form>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                      <button type="submit" class="btn btn-primary" id="confirm_change">OK</button>
                                    </div>
                                  </div>
                                  
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row m-3 p-3 text-center">
            <div class="col-md-6 text-left">
                <h4 class="text-primary">Sản phẩm</h4>
            </div>
            <div class="col-md-2">Đơn giá</div>
            <div class="col-md-2">Số lượng</div>
            <div class="col-md-2">Thành tiền</div>
        </div>

        <div class="row m-3 p-3 border text-center">
        {% for cartItem in list %}
            <div class="col-md-6 mb-3">
                <img class="product-img-small" src="{{cartItem.item.thumbnail}}" alt="">
                <span class="product_title-checkout">{{cartItem.item.title}}</span>
            </div>
            <div class="col-md-2">
                <span>{{cartItem.item.sale_price}}</span>
            </div>
            <div class="col-md-2">
                <span>{{cartItem.quantity}}</span>
            </div>
            <div class="col-md-2">
                <strong>{{cartItem.total}}</strong>
            </div>



            {% endfor %}
        </div>
        <div class="row m-3 p-3 border text-center">
            <div class="col-md-4">
                <h3>Đơn vị vận chuyển</h3>
            </div>
            <div class="col-md-4">
                <div class="form-group " >
                  <label for="">Chọn đơn vị vận chuyển</label>
                  <select class="form-control" name="" id="shipping" required>
                    <option value="" selected>-----Chọn-----</option>
                    {% for s in ship %}
                    <option value="{{s.id}}" data-fee="{{s.shipping_fee}}">{{s.title}}</option>
                 

                    {%endfor%}
                  </select>
                </div>
                <!-- <h4>Vận chuyển nhanh</h4>
                <span>J&T Express</span> -->
            </div>
            <div class="col-md-2">
                <a href="">Thay đổi</a>
            </div>
            <div class="col-md-2 ">
                <strong class="shipping-fee">0</strong>
            </div>
        </div>
        
        <div class="row m-3 p-3 border ">
            <div class="col-md-3">
                <h3 >Phương thức thanh toán</h3>
            </div>
            {% for method in payment%}
            <div class="col-md-3">
                <button class="btn " name="payment_method" data-id="{{method.id}}" >{{method.title}}</button>
            </div>
            <!-- <div class="col-md-3">
                <button class="btn " name="payment_method">Thanh toán khi nhận hàng</button>
            </div>
            <div class="col-md-3">
                <button class="btn " name="payment_method">Thanh toán ví airpay</button>
            </div> -->
            {%endfor%}

            
        </div>
        <div class="row p-3 border-top ">
            <div class="col-md-10 text-right mb-3">
                <h4 >Tổng tiền</h4>
            </div>
            <div class="col-md-2 text-center">
                <strong class="price-product">{{total}}</strong>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 text-right mb-3">
                <h5 >Phí vận chuyển</h5>
            </div>
            <div class="col-md-2 text-center">
                <strong class="shipping-fee price-product">0</strong>
            </div>
        </div>
        <div class="row ">
            <div class="col-md-10 text-right mb-3">
                <h4>Tổng thanh toán</h4>
            </div>
            <div class="col-md-2 text-center text-danger">
                <strong id="total" class="price-product">{{total}}</strong>
            </div>
        </div>
        <div class="row pr-5 d-flex justify-content-end">
           
            <div class="col-md-3 text-center text-danger">
              <button class="btn btn-danger w-100" id="order">Đặt hàng</button>
              <!-- <button class="btn btn-danger w-100" type="submit">Đặt hàng</button> -->
            </div>
        </div>

    
    </div>


  
    <!--Section: Products v.3-->
    <!--Pagination-->

</main>
{%endblock%}
<script>
   
</script>