Account/urls.py
from django.urls import path
from . import views
from nhaphang import views as view_nhaphang
from core.views import HomeView
app_name ='account'
urlpatterns = [
   
    path('home',HomeView.as_view(),name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),   
]

cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns = [
    path('',CartView.as_view(),name="index"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('update/',UpdateCart.as_view(),name="update"),
    path('addCart/',AddCart.as_view(),name="addToCart"),
    path('delete/',deleteItem.as_view(),name="delete"),
]

core/urls.py
from django.urls import path
from .views import HomeView
from product.views import ProductView
app_name='core'
urlpatterns = [
    path('',HomeView.as_view(),name="index"),
    path('product/',ProductView.as_view(),name='product_view')
]

order/urls.py
from django.urls import path
from .views import *
app_name='order'
urlpatterns = [
 
    # path('',CartView.as_view(),name="index"),
    path('addOrder/',AddOrder.as_view(),name="addOrder"),
    path('getOrder/',GetRatingOrder.as_view(),name="getOrder"),
    path('manage/',OrderManage.as_view(),name="manage"),
    path('feedback/',FeedBack.as_view(),name="feedback"),
    path('viewfeedback/',ViewFeedback.as_view(),name="viewfeedback"),
    path('checkfeedback/',CheckFeedback.as_view(),name="checkfeedback"),
    path('status/update/',UpdateStatus.as_view(),name="updateStatus"),
    path('status/<int:type>',OrderStatus.as_view(),name="status"),
    path('delete_comment/',Delete_Comment.as_view(),name="delete_comment"),
    path('ignore_comment/',Ignore_Comment.as_view(),name="ignore_comment"),
    path('reply_comment/',Reply_Comment.as_view(),name="reply_comment"),
    
]

shopapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Account.urls')),
    path('',include('core.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('user/',include('user.urls')),
    path('order/',include('order.urls')),
    path('nhaphang/',include('nhaphang.urls')),
]

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns = [
    # path('search/',CategoryView.as_view(),name="search"),
   
    path('purchase/',OrderPurchase.as_view(),name="purchase"),
    path('address/add',Add_Address.as_view(),name="add"),
    path('address/edit/',Edit_Address.as_view(),name="edit"),
    path('address/delete/',Delete_Address.as_view(),name="delete"),
    path('address/',AddressView.as_view(),name="address"),
    path('comment/',CommentProduct.as_view(),name="comment"),
    path('address/change_default_address/',change_default_address.as_view(),name="delete"),

]

templates/homepage/banner.html
<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Best Offer</h4>
          <h2>New Arrivals On Sale</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Flash Deals</h4>
          <h2>Get your best products</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Last Minute</h4>
          <h2>Grab last minute deals</h2>
        </div>
      </div>
    </div>
  </div>

templates/homepage/category.html
<div id="list-example" class="list-group">
  <h2>Danh mục sản phẩm</h2>
  <ul class="navbar-nav mr-auto">
    {% for category in categorys %}
    <li class="nav-item ">
      <a class="nav-link" >
        <a href="{% url 'category' category.slug%}" class="list-group-item list-group-item-action" href="#list-item-1">{{category.title}}</a>
      </a>
    </li>
    {%endfor%}
   

  </ul>
 
 
</div>

    <!-- Links -->
    
    <!-- Links -->

    <!-- <form class="form-inline" method="POST" action="{% url 'search'%}">
        {% csrf_token %}
      <div class="md-form my-0">
        <input name= "search" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      
      </div>
    </form> -->
 
<!--/.Navbar-->

templates/homepage/footer.html
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="inner-content">
          <p>Copyright &copy; 2020 Sixteen Clothing Co., Ltd.
        
        - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/homepage/header.html
<header class="">

  <nav class="navbar navbar-expand-lg ">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index'%}"><h2>Hệ thống <em>BoEC</em></h2></a>
      <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'product:search'%}">
        {%csrf_token%}
        <input name="text_search"class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:index'%}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li> 
          {%if user.groups.all.0.name == 'customer'%}
          <li class="nav-item">
            <a class="nav-link" href="/product">Our Products</a>
          </li>
          {%endif%}
          {%if user.groups.all.0.name == 'customer'%}
          <li class="nav-item">
            <a class="nav-link" href="/cart"><i class="fas fa-shopping-cart"></i></a>
          </li>
          {%endif%}

          {%if user.groups.all.0.name == 'nvkho'%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nhaphang:kho'%}">QL Kho</a>
          </li>
          {%endif%}

          {%if user.groups.all.0.name == 'nvbh'%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'order:manage'%}">đơn hàng</a>
          </li>
          {%endif%}
          {%if user.groups.all.0.name == 'nvbh'%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'order:feedback'%}">Feedback</a>
          </li>
          {%endif%}
          {%block header_block%}
          {%endblock%}
          <li class="nav-item">
            {% if user.id is None %}
            <a class="nav-link" href="/account/login"> Login</a>
            
           
            {% else %}
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="far fa-user"></i>{{user}}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <!-- <a class="dropdown-item" href="#">{{user.groups.all}}</a> -->
                {%if user.groups.all.0.name == 'customer'%}
                <a class="dropdown-item" href="{% url 'user:purchase'%}">Đơn mua</a>
                {%endif%}
                {%if user.groups.all.0.name == 'customer'%}
                <a class="dropdown-item" href="{% url 'user:address'%}">Địa chỉ</a>
                {%endif%}
                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
              </div>
            </div>
              {%endif %}  
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<!-- Page Content -->
<!-- Banner Starts Here -->

templates/homepage/home-page.html
{% extends 'homepage/base.html' %}
{% load static %}

  <!--Main layout-->

  
  {%block contentblock%}
     {% include 'homepage/banner.html' %}
  <main>
    <div class="container">

      <!--Navbar-->
     

      <!--Section: Products v.3-->
       
      <div class="latest-products">
        <div class="container">
        
          <div class="row">
            <div class="col-md-12">
              <div class="section-heading">
                <h2>Latest Products</h2>
                <a href="{% url 'core:product_view' %}">view all products <i class="fa fa-angle-right"></i></a>
              </div>
            </div>
            {% for pro in page_obj %}
            <div class="col-md-4">
              <div class="product-item">
                <a href="{% url 'product:detail' pro.id %}"><img src="{{pro.thumbnail}}" alt=""></a>
                <div class="down-content">
                  <a href="#"><h5 class="product_title">{{pro.title}}</h5></a>
                  <br>
                  <div><b>{{pro.sale_price}}</b></div>
                  
                  <ul class="stars">
                    <li><i class="fa fa-star"></i></li>
                    <li><i class="fa fa-star"></i></li>
                    <li><i class="fa fa-star"></i></li>
                    <li><i class="fa fa-star"></i></li>
                    <li><i class="fa fa-star"></i></li>
                  </ul>
                  <span>Reviews (24)</span>
                </div>
              </div>
            </div>
            
            {% endfor %}
            <div class="col-md-12">
              <div class="pages">
               
                  <ul class="pages">
                  {% if page_obj.has_previous %}
                  <li>
                    <a href="?page=1"><i class="fa fa-angle-double-left"></i></a>
                  </li>
                  <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                  {% endif %}
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <span>
                          <li>
                            <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                          </li>
                        </span>
                       <span> <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a></li></span>
                    {% endif %}
                
            </div>
            </div>
            </div>
         
          </div>
          
        </div>
      
      </div>
  
      <!-- <div class="best-features">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-heading">
                <h2>About Sixteen Clothing</h2>
              </div>
            </div>
            <div class="col-md-6">
              <div class="left-content">
                <h4>Looking for the best products?</h4>
                <p><a rel="nofollow" href="https://templatemo.com/tm-546-sixteen-clothing" target="_parent">This template</a> is free to use for your business websites. However, you have no permission to redistribute the downloadable ZIP file on any template collection website. <a rel="nofollow" href="https://templatemo.com/contact">Contact us</a> for more info.</p>
                <ul class="featured-list">
                  <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                  <li><a href="#">Consectetur an adipisicing elit</a></li>
                  <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                  <li><a href="#">Corporis, omnis doloremque</a></li>
                  <li><a href="#">Non cum id reprehenderit</a></li>
                </ul>
                <a href="about.html" class="filled-button">Read More</a>
              </div>
            </div>
            <div class="col-md-6">
              <div class="right-image">
                <img src="{% static 'assets/images/feature-image.jpg'%}" alt="">
              </div>
            </div>
          </div>
        </div>
      </div> -->
  
  
      <!--Section: Products v.3-->
      {%endblock%}
      <!--Pagination-->
     
 
  <!--Main layout-->

  <!--Footer-->
  
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->