cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns = [
    path('',CartView.as_view(),name="index"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('update/',UpdateCart.as_view(),name="update"),
    path('addCart/',AddCart.as_view(),name="addToCart"),
    path('delete/',deleteItem.as_view(),name="delete"),
]

order/urls.py
from django.urls import path
from .views import *
app_name='order'
urlpatterns = [
 
    # path('',CartView.as_view(),name="index"),
    path('addOrder/',AddOrder.as_view(),name="addOrder"),
    path('getOrder/',GetRatingOrder.as_view(),name="getOrder"),
    path('manage/',OrderManage.as_view(),name="manage"),
    path('feedback/',FeedBack.as_view(),name="feedback"),
    path('viewfeedback/',ViewFeedback.as_view(),name="viewfeedback"),
    path('checkfeedback/',CheckFeedback.as_view(),name="checkfeedback"),
    path('status/update/',UpdateStatus.as_view(),name="updateStatus"),
    path('status/<int:type>',OrderStatus.as_view(),name="status"),
    path('delete_comment/',Delete_Comment.as_view(),name="delete_comment"),
    path('ignore_comment/',Ignore_Comment.as_view(),name="ignore_comment"),
    path('reply_comment/',Reply_Comment.as_view(),name="reply_comment"),
    
]

shopapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Account.urls')),
    path('',include('core.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('user/',include('user.urls')),
    path('order/',include('order.urls')),
    path('nhaphang/',include('nhaphang.urls')),
]

order/models.py
from django.db import models
from cart.models import Cart
from user.models import CustomerUser
from product.models import Product
# Create your models here.
STATUS = [
    (1, 'Chờ xác nhận'),
    (2, 'Đang xử lí'),
    (3, 'Đang giao hàng'),
    (4, 'Đã hoàn thành'),
    (5, 'Đã hủy'),
]    
class Shipping(models.Model):
    title = models.CharField(max_length=255)
    shipping_fee = models.FloatField(default=0)
    def __str__(self):
        return self.title
class Payment(models.Model):
    title = models.CharField(max_length=255)
    def __str__(self):
        return self.title
class Order(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    shipping_address =models.CharField(default='',max_length=255)
    total = models.FloatField(default=0)
    ship = models.ForeignKey(Shipping,on_delete=models.CASCADE,null=True,blank=True)
    paymentMethod = models.ForeignKey(Payment,on_delete=models.CASCADE,null=True,blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(
      
        choices=STATUS,
        default=STATUS[0][0],
    )
    is_complete =models.BooleanField(default=False)

class OrderDetail(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    product_name= models.CharField(max_length=255,null=True)
    image= models.CharField(max_length=255,null=True)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0)
   
    is_rating = models.BooleanField(default=False)
    def formatPrice(self):
        self.price ="₫{:,.0f}".format(self.price)
        return self.price

order/views.py
from django.db import reset_queries
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.serializers import serialize
from django.shortcuts import redirect, render
from django.views import View
from cart.models import *
from .models import *
from user.models import *
from order.feedback_process.classify import check


# Create your views here.
class AddOrder(View):
    def post(self,request):
        if request.user.is_authenticated:
            cart = Cart.objects.get(user=request.user)
            cartItem = cart.cartitem_set.all()
            total=request.POST.get('total')
            shipping_id =request.POST.get('shipping_id')
            payment_id =request.POST.get('payment_id')
            ship= Shipping.objects.get(pk = shipping_id)
            pay =Payment.objects.get(pk = payment_id)
            address_user=Address.objects.get(user= request.user,default=True)
            shipping_address = address_user.street +',' +  address_user.apartment_number+','+ address_user.district+ ','+address_user.city
            order =Order.objects.create(user=request.user,cart= cart,shipping_address=shipping_address,ship=ship, paymentMethod=pay,total=total)
            for cart_item in cartItem:
                OrderDetail.objects.create(order= order, product= cart_item.item,product_name=cart_item.item.title, image =cart_item.item.thumbnail,quantity= cart_item.quantity,price=cart_item.item.sale_price)
                # HttpResponse(item.item.sale_price)
            cart.cartitem_set.all().delete()    
            return HttpResponse(1)
class GetRatingOrder(View):
    def get(self,request):
        if request.user.is_authenticated:
            id= request.POST.get('id')
            order =Order.objects.get(pk=18, user=request.user)   
            o = list(OrderDetail.objects.filter(is_rating=True, order=order).values())
         
            comment =list(Comment.objects.filter(order_id=18).values())
        return JsonResponse({"o":o,"c":comment},safe=False)
     
    def post(self,request):
        if request.user.is_authenticated:
            id= request.POST.get('id')
            order =Order.objects.get(pk=id, user=request.user)   
            o = list(OrderDetail.objects.filter(is_rating=True, order=order).values())
         
            comment =list(Comment.objects.filter(order_id=id).values())
        return JsonResponse({"o":o,"c":comment},safe=False)

class FeedBack(View):
    def get(self,request):
        comments = Comment.objects.filter(checked = True)
        context ={}
        context['comments'] = comments
        return render(request,"order/viewfeedback.html",context)
class ViewFeedback(View):
    def get(self,request):
        comments = Comment.objects.filter(checked = True)
        context ={}
        context['comments'] = comments
        return render(request,"order/viewfeedback.html",context)
class CheckFeedback(View):
    def get(self,request):
        comments = Comment.objects.filter(checked = False)
        for cmt in comments:
            res =check(cmt.comment)
            # print(cmt.comment)
            cmt.type_comment =res 
            cmt.save()

        context ={}
        context['comments'] = comments
        return render(request,"order/checkfeedback.html",context)
class Delete_Comment(View):
    def post(self,request):
        id = request.POST.get('id_cmt')
        Comment.objects.filter(id=id).delete()
        return HttpResponse(1)

class Ignore_Comment(View):
    def post(self,request):
        id = request.POST.get('id_cmt')
        comment = Comment.objects.get(id=id)
        comment.checked = True
        comment.save()
        return HttpResponse(1)
class Reply_Comment(View):
    def post(self,request):
        id_cmt = request.POST.get('id_cmt')
        print("id comment",id_cmt)
        content_rep = request.POST.get('content_rep')
        comment=Comment.objects.get(id=id_cmt)
        comment.checked = True
        comment.save()
        rep_cmt = ReplyComment.objects.create(comment=comment,content=content_rep)
        rep_cmt.save()
        return HttpResponse(1)

class OrderManage(View):
    def get(seft,request):
        if request.user.is_authenticated:
            orders =Order.objects.all()
            context={}
            context['orders']= orders
            return render(request,"order/manage.html",context)
        else:
            return redirect('account:login')
    def post(seft,request):
        if request.user.is_authenticated:
            orders =Order.objects.all()
            context={}
            context['orders']= orders
            return render(request,"order/manage.html",context)
        else:
            return redirect('account:login')
class OrderStatus(View):
    def get(seft,request,type):
        status =type
        if status==0:
            order = Order.objects.all()
            count = order.count()
        else:
            order = Order.objects.filter(status=status)
            count = order.count()
        
       
        context={}
        context['orders']=order
        context['active'] =status    
        context['count']=count
       
        return render(request,"order/manage.html",context)
    def post(seft,request,type):
        status =type
        count={}
        if status==0:
            order = Order.objects.all()
            count = order.count()
        else:
            order = Order.objects.filter(status=status)
            count = order.count()
        

        context={}
        context['orders']=order
        context['active'] =status    
        context['count']=count
        return render(request,"order/manage.html",context)
        # return JsonResponse(order,safe=False)
class UpdateStatus(View):
    def get(seft,request,order,type):
        Order.objects.filter()
        return HttpResponse(1)
    def post(seft,request):
        order = request.POST.get('orderid')
        type = request.POST.get('type')
        type1= int(type)+1
        Order.objects.filter(pk=order,status=int(type)).update(status=type1)
        # return HttpResponse(order)
        return HttpResponseRedirect(seft.request.META.get('HTTP_REFERER'))
      

templates/order/checkfeedback.html
{%extends 'order/feedback.html'%}
{%block feedback_process%}
<table class="table table-hover mt-5">
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th>Time</th>
        <th>Type</th>
        <th>Process</th>
      </tr>
    </thead>
    <tbody>
      {%for cmt in comments%}
      <tr>
        <td>{{cmt.user}}</td>
        <td>{{cmt.comment}}</td>
        <td>{{cmt.time}}</td>
        <td class="{% if cmt.type_comment == 'Positive' %}bg-success{%endif%}{% if cmt.type_comment == 'Negative' %}bg-danger{%endif%}{% if cmt.type_comment == 'Neutral' %}bg-secondary{%endif%}">{{cmt.type_comment}}</td>
        <td><button name="delete_cmt" data-id="{{cmt.id}}">Delete</button> <button type="button" id="replycomment" data-id="{{cmt.id}}" data-toggle="modal" data-target="#reply_cmt_form">Reply</button><button name="ignore_cmt" data-id="{{cmt.id}}">Ignore</button></td>
      </tr>
      {%endfor%}
    </tbody>
    <div class="modal fade" id="reply_cmt_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Reply Feedback</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label for="">Nội dung</label>
              <input type="text"
                class="form-control" name="" id="content_rep"  placeholder="" >
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="confirmreply">OK</button>
          </div>
        </div>
      </div>
    </div>
  </table>
{%endblock%}

templates/order/feedback.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block contentblock %}
<main style="padding-top:50px;">
    <br>
    <br>
    <div class="p-5">
        <div class="nav nav-tabs">
            <div class="nav-item mr-5"><a href="{% url 'order:viewfeedback'%}"><h3>Xem phản hồi</h3></a></div>
            <div class="nav-item"><a href="{% url 'order:checkfeedback'%}"><h3>Xử lý phản hồi</h3></a></div>
        </div>
        {%block feedback_process%}
        {%endblock%}
    </div>
    </main>
  {%endblock%}

templates/order/manage.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block contentblock %}

<main style="padding-top:50px;">
  <div class="container products">
      <div class="row">
          <div class="col-md-12">
              <h3>Quản lí đơn đặt hàng</h3>
              <form  method="post" id="form_status">
                  {%csrf_token%}
              </form>  
          </div>
      </div>
      <div class="container mt-3">
        <h2>Trạng thái đơn hàng</h2>
        <br>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link status_order {% if active == 0 %}active{%endif%}" data-toggle="tab" href="#all" data-type="all">Tất cả</a>
          </li>
          <li class="nav-item">
            <a class="nav-link status_order {% if active == 1 %}active{%endif%}" data-toggle="tab" href="#choxacnhan" data-type="1">Chờ xác nhận</a>
          </li>
          <li class="nav-item">
            <a class="nav-link status_order {% if active == 2 %}active{%endif%}" data-toggle="tab" href="#dangxuli" data-type="2">Đang xử lí</a>
          </li>
          <li class="nav-item">
            <a class="nav-link status_order {% if active == 3 %}active{%endif%}" data-toggle="tab" href="#danggiaohang" data-type="3">Đã chuyển cho đơn vị vận chuyển</a>
          </li>
         
          <li class="nav-item ">
            <a class="nav-link status_order {% if active == 4 %}active{%endif%}" data-toggle="tab" href="#dahoanthanh" data-type="4">Đã hoàn thành</a>
          </li>
          <li class="nav-item">
            <a class="nav-link status_order {% if active == 5 %}active{%endif%}" data-toggle="tab" href="#dahuy" data-type="5">Đã hủy</a>
          </li>
        </ul>
      
        <!-- Tab panes -->
        <div class="tab-content">
          <div id="all" class="container tab-pane active"><br>
            <div class="row">
                <div class="col-md-12">
                    <table class="table container">
                        <thead class="thead-light ">
                            <tr>
                                <th>ID</th>
                               
                                <th style="width:494px" class="text-center">Sản phẩm</th>
                               
                                
                                <th>Tổng tiền</th>
                                <th>Trạng thái</th>
                                <th>Hành động</th>
                            </tr>
                          </thead>
                    </table>
                </div>
            </div>
            {%for or in orders%}
            <div class="row m-3 p-3 border text-center d-flex align-items-center">
                {%for o in or.orderdetail_set.all%}
            <div class="col-md-6 mb-3">
                <img class="product-img-small" src="{{o.image}}" alt="">
                <span class="product_title-checkout">{{o.product_name}}</span>
            </div>
            
            <div class="col-md-2">
                <span>{{or.total}}</span>
            </div>
            <div class="col-md-2">
               
                {% if or.status == 1 %}
                <span>Chờ xác nhận</span>
                {%elif or.status == 2 %}
                <span>Đang xử lí</span>
                {%elif or.status == 3 %}
                <span>Đang giao hàng</span>
                {%elif or.status == 4 %}
                <span>Đang hoàn thành</span>
                {%elif or.status == 5 %}
                <span>Đang hủy</span>
                {% endif %}
                <!-- {{or.status}} -->
            </div>
            {% endfor %}
            <div class="col-md-2 ">
               
                {% if or.status == 1 %}
                <form action="{% url 'order:updateStatus'%}" method="post">
                  <input type="hidden"  name="orderid" value="{{or.id}}">
                  <input type="hidden"  name="type" value="{{or.status}}">
                  <button type="submit">Xác nhận</button>
                  {% csrf_token%}
                </form>
                {%elif or.status == 2 %}
                <form action="{% url 'order:updateStatus'%}" method="post">
                  <input type="hidden"  name="orderid" value="{{or.id}}">
                  <input type="hidden"  name="type" value="{{or.status}}">
                  <button type="submit">Đóng gói xong</button>
                  {% csrf_token%}
                </form>
                {%elif or.status == 3 %}
                <form action="{% url 'order:updateStatus'%}" method="post">
                  <input type="hidden"  name="orderid" value="{{or.id}}">
                  <input type="hidden"  name="type" value="{{or.status}}">
                  <button type="submit">Đã giao</button>
                  {% csrf_token%}
                </form>
                {%elif or.status == 4 %}
                <form action="{% url 'order:updateStatus'%}" method="post">
                  <input type="hidden"  name="orderid" value="{{or.id}}">
                  <input type="hidden"  name="type" value="{{or.status}}">
                  <button type="submit">Kết thúc</button>
                  {% csrf_token%}
                </form>
                {%elif or.status == 5 %}
                <form action="{% url 'order:updateStatus'%}" method="post">
                  <input type="hidden"  name="orderid" value="{{or.id}}">
                  <input type="hidden"  name="type" value="{{or.status}}">
                  <button type="submit">Xác nhận hủy</button>
                  {% csrf_token%}
                </form>
                {% endif %}
                <!-- {{or.status}} -->
            </div>



          
        </div>          
        {%endfor%}             
                          
          </div>
          <!-- <div id="1" class="container tab-pane fade"><br>
            <h3>Menu 1</h3>
            <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>
          <div id="2" class="container tab-pane fade"><br>
            <h3>Menu 2</h3>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
          </div>
          <div id="3" class="container tab-pane fade"><br>
            <h3>Menu 2</h3>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
          </div>
          <div id="4" class="container tab-pane fade"><br>
            <h3>Menu 2</h3>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
          </div>
          <div id="5" class="container tab-pane fade"><br>
            <h3>Menu 2</h3>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p> -->
          </div>
        </div>
      </div>
      
    
    
                        
                        
                      
              </table>
          </div>
      </div>
  </div> 
</main>
{%endblock%}

templates/order/viewfeedback.html
{%extends 'order/feedback.html'%}
{%block feedback_process%}
<table class="table table-hover mt-5">
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th>Time</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      {%for cmt in comments%}
      <tr>
        <td>{{cmt.user}}</td>
        <td>{{cmt.comment}}</td>
        <td>{{cmt.time}}</td>
        <td class="{% if cmt.type_comment == 'Positive' %}bg-success{%endif%}{% if cmt.type_comment == 'Negative' %}bg-danger{%endif%}{% if cmt.type_comment == 'Neutral' %}bg-secondary{%endif%}">{{cmt.type_comment}}</td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  {%endblock%}