cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns = [
    path('',CartView.as_view(),name="index"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('update/',UpdateCart.as_view(),name="update"),
    path('addCart/',AddCart.as_view(),name="addToCart"),
    path('delete/',deleteItem.as_view(),name="delete"),
]

product/urls.py
from django.urls import path
from .views import *
app_name='product'
urlpatterns = [
 
    path('',ProductView.as_view(),name="index"),
    path('category/<slug:slug>/',CategoryView.as_view(),name="category"),
    path('detail/<int:id>/',DetailView.as_view(),name="detail"),
    path('search/',SearchProduct.as_view(),name="search"),
    # path('create/',CreateProduct.as_view(),name="create"),
]

shopapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Account.urls')),
    path('',include('core.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('user/',include('user.urls')),
    path('order/',include('order.urls')),
    path('nhaphang/',include('nhaphang.urls')),
]

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns = [
    # path('search/',CategoryView.as_view(),name="search"),
   
    path('purchase/',OrderPurchase.as_view(),name="purchase"),
    path('address/add',Add_Address.as_view(),name="add"),
    path('address/edit/',Edit_Address.as_view(),name="edit"),
    path('address/delete/',Delete_Address.as_view(),name="delete"),
    path('address/',AddressView.as_view(),name="address"),
    path('comment/',CommentProduct.as_view(),name="comment"),
    path('address/change_default_address/',change_default_address.as_view(),name="delete"),

]

order/models.py
from django.db import models
from cart.models import Cart
from user.models import CustomerUser
from product.models import Product
# Create your models here.
STATUS = [
    (1, 'Chờ xác nhận'),
    (2, 'Đang xử lí'),
    (3, 'Đang giao hàng'),
    (4, 'Đã hoàn thành'),
    (5, 'Đã hủy'),
]    
class Shipping(models.Model):
    title = models.CharField(max_length=255)
    shipping_fee = models.FloatField(default=0)
    def __str__(self):
        return self.title
class Payment(models.Model):
    title = models.CharField(max_length=255)
    def __str__(self):
        return self.title
class Order(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    shipping_address =models.CharField(default='',max_length=255)
    total = models.FloatField(default=0)
    ship = models.ForeignKey(Shipping,on_delete=models.CASCADE,null=True,blank=True)
    paymentMethod = models.ForeignKey(Payment,on_delete=models.CASCADE,null=True,blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(
      
        choices=STATUS,
        default=STATUS[0][0],
    )
    is_complete =models.BooleanField(default=False)

class OrderDetail(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    product_name= models.CharField(max_length=255,null=True)
    image= models.CharField(max_length=255,null=True)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0)
   
    is_rating = models.BooleanField(default=False)
    def formatPrice(self):
        self.price ="₫{:,.0f}".format(self.price)
        return self.price

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from product.models import Product
from django.db.models.deletion import CASCADE
# Create your models here.



class CustomerUser(AbstractUser):
    phone_number =models.CharField(default='',max_length=15)
class Address(models.Model):
    id = models.AutoField(primary_key=True)
    reciever = models.CharField(default='Name of reciever',max_length=255)
    phone_reciever = models.CharField(default='reciever\'s phone number',max_length=255)
    user = models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    street =models.CharField(default='',max_length=255)
    apartment_number =models.CharField(default='',max_length=255)
    district=models.CharField(default='',max_length=255)
    city=models.CharField(default='',max_length=255)
    default=models.BooleanField(default=False)
    def ToString(self):
        return self.street+"," +self.apartment_number+","+self.district+","+ self.city

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    checked = models.BooleanField(default=False)
    time = models.DateField(auto_now_add=True)
    user = models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField(default='')
    rating = models.IntegerField(default=0)
    order_id = models.IntegerField(default=0)
    create_at =models.DateTimeField(auto_now_add=True)
    type_comment = models.CharField(default='',max_length=200)

class ReplyComment(models.Model):
    id = models.AutoField(primary_key=True)
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE)
    content = models.CharField(default='cảm ơn bạn đã mua sản phẩm!', max_length=250)
    time = models.DateField(auto_now_add=True)

user/views.py
from order.models import Order
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from user.models import Comment,Address
from product.models import Product
from order.models import *

# Create your views here.


class OrderPurchase(View):
    def get(seft, request):
        if request.user.is_authenticated:
            context={}
            detail =[]
            order =Order.objects.filter(user=request.user)
            context['order'] = order
           
            # return HttpResponse(detail)
            return render(request,"user/purchase.html",context)

class AddressView(View):
    def get(seft,request):
      
        context={}
        addresses = Address.objects.filter(user=request.user)
        for add in addresses:
            add.address = add.ToString()
        context['address'] =addresses
      
        # return HttpResponse(addresses)
        return render(request,"user/address.html",context)
    def post(seft,request):
        address_id = request.POST.get('address_id')
        Address.objects.filter(user=request.user,default=True).update(default=False)
        Address.objects.filter(pk=address_id).update(default=True)
       
        return HttpResponse(1 ,"user:address")
class Add_Address(View):
    def post(seft,request):
        reciever = request.POST.get('reciever')
        phone_reciever = request.POST.get('phone_reciever')
        street =request.POST.get('street')
        apartment =request.POST.get('apartment')
        district =request.POST.get('district')
        city =request.POST.get('city')
        Address.objects.create(user= request.user,reciever= reciever,phone_reciever=phone_reciever, street= street,apartment_number= apartment,district=district,city=city)
        return HttpResponse(1)
class Edit_Address(View):
    def post(seft,request):
        id= request.POST.get('id')
        fullname =request.POST.get('reciever')
        print('fullname:',fullname)
        phone =request.POST.get('phone')
        street =request.POST.get('street')
        apartment =request.POST.get('apartment')
        print('apartment:',apartment)
        district =request.POST.get('district')
        city =request.POST.get('city')
        add =Address.objects.get(pk=id)
        add.reciever = fullname
        add.phone_reciever = phone
        add.street =street
        add.apartment_number=apartment
        add.district =district
        add.city=city
        add.save()
        print('edited.')
        return HttpResponse(1)
class Delete_Address(View):
    def post(seft,request):
        id= request.POST.get('id')
        add =Address.objects.get(pk=id)
        add.delete()
        return redirect("user:address")
        
class CommentProduct(View):
    def post(seft,request):
        if request.user.is_authenticated:
            product_id =request.POST.get('id_pro')
            order_id =request.POST.get('id_order')
            score =request.POST.get('score')
            comment =request.POST.get('comment')
            pro = Product.objects.get(id= product_id)

          
            Comment.objects.create(user = request.user, product=pro,comment=comment,rating=int(score),order_id=int(order_id))
            OrderDetail.objects.filter(order =Order.objects.get(pk=order_id),product=pro).update(is_rating=True)
            return HttpResponse(pro)
        # return HttpResponse(1)
        
class change_default_address(View):
    def post(self,request):
        id_address = request.POST.get('id_address')
        print(id_address)
        all_address = Address.objects.filter(user=request.user)
        for add in all_address:
            print(add.id)
            if int(add.id) == int(id_address):
                print("Changed")
                add.default = True
                add.save()
            else:
                add.default = False
                add.save()
        return  HttpResponse(1 ,"cart:checkout")

templates/user/address.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block contentblock %}
  <!--Main layout-->
  <main style="padding-top:100px;">
      <div class="card-body container">
         <div class="row">
             <div class="col-md-12 d-flex justify-content-between border-bottom mb-3">
                <h2 class="pb-2 ">Địa chỉ của tôi</h2>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addAddress" data-id="1">
                  Thêm địa chỉ
                  </button>
             </div>
         </div>
          {% for add in address %}
          <div class="row border-bottom  pl-4">
            
            <div class="col-md-2">
                <h6 class="my-4">Họ và tên:</h6>
                <h6 class="my-4">Số điện thoại: </h6>
                <h6 class="my-4">Địa chỉ: </h6>
            </div>
            <div class="col-md-6 address_user">
                <h6 class="my-4 name">{{ add.reciever }} </h6>
                <h6 class="mb-4">{{add.phone_reciever}} </h6>
                <h6 class="my-4">{{add.ToString}}</h6>
            </div>
            <div class="col-md-4">
                {% if add.default %}  <button class="btn" name="btn-default-address" data-id="{{add.id}}"  disabled>Thiết lập mặc định</button>{%else%}
               <button class="btn" name="btn-default-address" data-id="{{add.id}}"  >Thiết lập mặc định</button>
               {%endif%}
               
               <button type="button" class="btn btn-primary"
                data-id="{{add.id}}"
                data-reciever = "{{add.reciever}}"
                data-phone_reciever = "{{add.phone_reciever}}"
                data-street="{{add.street}}" 
                data-apartment="{{add.apartment_number}}" 
                data-district="{{add.district}}" 
                data-city="{{add.city}}" 

                data-toggle="modal" data-target="#editAddress" id="edit_address">
                Sửa
              </button>
              <form action="/user/address/delete/" method="post">
                <input type="hidden" name="id" value="{{add.id}}">
                <button onClick="confirm('Bạn có chắc chắn muốn xóa?')"  class="btn btn-danger " type="submit">Xóa</button>
                {%csrf_token%}
              </form>
            
            </div>
          </div>
          {% endfor %}
          <!-- Thêm địa chỉ -->
          <div class="modal fade" id="addAddress" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="form-group">
                    <label for="">Người nhận</label>
                    <input type="text"
                      class="form-control" name="" id="reciever"  placeholder="" >
                  </div>
                  <div class="form-group">
                    <label for="">Số điện thoại</label>
                    <input type="text"
                      class="form-control" name="" id="phone_reciever"  placeholder="" >
                  </div>
                 <div class="form-group">
                   <label for="">Street</label>
                   <input type="text"
                     class="form-control" name="" id="street"  placeholder="" >
                 </div>
                 <div class="form-group">
                   <label for="">Apartment</label>
                   <input type="text"
                     class="form-control" name="" id="apartment"  placeholder="">
                  
                 </div>
                 <div class="form-group">
                   <label for="">District</label>
                   <input type="text"
                     class="form-control" name="" id="district"  placeholder="">
                  
                 </div>
                 <div class="form-group">
                   <label for="">City</label>
                   <input type="text"
                     class="form-control" name="" id="city"  placeholder="">
                  
                 </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary" id="add_address">Save changes</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Sửa địa chỉ -->
          <div class="modal fade" id="editAddress" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Sửa thông tin</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form method="POST"> 
                    <div class="form-group">
                      <label for="">Người nhận</label>
                      <input type="text"
                        class="form-control" name="" id="editreciever"  placeholder="" >
                    </div>
                    <div class="form-group">
                      <label for="">Số điện thoại</label>
                      <input type="text"
                        class="form-control" name="" id="editphone"  placeholder="" >
                    </div>
                    <div class="form-group">
                      <label for="">Street</label>
                      <input type="text"
                        class="form-control" name="" id="editstreet"  placeholder="" >
                    </div>
                    <div class="form-group">
                      <label for="">Apartment</label>
                      <input type="text"
                        class="form-control" name="" id="editapartment"  placeholder="">
                      
                    </div>
                    <div class="form-group">
                      <label for="">District</label>
                      <input type="text"
                        class="form-control" name="" id="editdistrict"  placeholder="">
                    </div>
                    <div class="form-group">
                      <label for="">City</label>
                      <input type="text"
                        class="form-control" name="" id="editcity"  placeholder=""> 
                    </div>
                </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary" name="edit_address">Xác nhận</button>
                </div>
              </div>
            </div>
          </div>
      </div>
      
  </main>
{%endblock%}

  

templates/user/purchase.html
{% extends 'homepage/base.html' %}
{% load static %}


{% block contentblock %}
<!--Main layout-->
<main style="padding-top:100px;">
  <div class="cart container-fluid">
    <h2>Đơn hàng</h2>
    <div class="row mt-5 pl-4">
      <div class="col-md-3 border bg-light">
        <div class="total m-3">
          <div class="row py-4 border">
            <div class="col-md-12 d-flex justify-content-between">
              <strong>{{request.user}}</strong>
              <!-- <span>{{total}}</span> -->
            </div>
          </div>
          <div class="row py-4 ">
            <div class="col-md-12 ">
              <h4>
                <a href="" type="submit" class="btn">Tài khoản của tôi</a>
              </h4>
              <h4>
                <a href="{% url 'user:address'%}" type="submit" class="btn">Địa chỉ</a>
              </h4>
              <h4>
                <a href="{% url 'user:purchase'%}" type="submit" class="btn">Đơn mua</a>
              </h4>
                
             
             
             
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9 ">
        <div class="content bg-light  p-2">
          {% for ord in order %}
          <div class="row">
            <div class="col-md-12">
              {{or.status}}
            </div>
          </div>
          <div class="row mb-3 border d-flex align-items-center">
            {%for item in ord.orderdetail_set.all %}
            <div class="col-md-7">
             
              <a href="{% url 'product:detail' item.product.id %}">
                <img src="{{item.product.thumbnail}}" class="product-img-md" alt="" style="width:80px; height:80px;">
                <span class="product_title-checkout" style="width: 400px;">{{item.product.title}}</span>
              </a> 
              <strong>x {{item.quantity}}</strong>

            



            </div>
            <div class="col-md-3 text-center">
              <strong class="price-product text-danger">{{item.price}}</strong>

            </div>
            {% if not item.is_rating %}
              <div class="col-md-2"><button type="button" class="btn btn-primary " data-toggle="modal"
                  data-target="#comment_product" data-order="{{ord.id}}"data-id="{{item.product.id}}" data-img="{{item.product.thumbnail}}"
                  data-title="{{item.product.title}}">
                  Đánh giá
                </button></div>
              {%else%}
              <div class="col-md-2"><button disabled type="button" class="btn btn-outline-danger  "
                >
                Đã đánh giá
              </button></div>
              {%endif%}
            {%endfor%}
            <div class="col-md-9 text-right">
              <h4> Tổng tiền</h4>
            </div>
            <div class="col-md-3 text-center">
              <h4 class=""> <span class="price-product text-danger">{{ord.total}}</span></h4>
            </div>
            <div class="col-md-12 d-flex justify-content-end pr-5 py-3 mr-5">
              <div class="col-md-2"><button type="button" class="btn btn-primary " data-toggle="modal"
                  data-target="#viewcomment" data-id="{{ord.id}}">
                  Xem đánh giá
                </button></div>
              <div class="btn btn-danger" style="width: 120px;">Hủy</div>
            </div>
          </div>
          {% endfor %}


        </div>
      </div>

    </div>
    <div class="modal fade" id="viewcomment" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="content_rating">

            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="add_address">Đánh giá</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="comment_product" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="product_rating">
              
            </div>

         
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="add_address">Đánh giá</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--Section: Products v.3-->
  <!--Pagination-->

</main>
{%endblock%}